31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1245)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.initialise(WMQMessageProducer.java:837)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.<init>(WMQMessageProducer.java:1221)
                               : com.ibm.msg.client.wmq.internal.WMQSession.createProducer(WMQSession.java:1122)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.createProducer(JmsSessionImpl.java:1503)
                               : com.ibm.mq.jms.MQSession.createProducer(MQSession.java:661)
                               : com.ibm.mq.demo.TicketRequester.put(TicketRequester.java:86)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:65)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2195' ('MQRC_UNEXPECTED_ERROR').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1245)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$800(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.initialise(WMQMessageProducer.java:837)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.<init>(WMQMessageProducer.java:1221)
                               : com.ibm.msg.client.wmq.internal.WMQSession.createProducer(WMQSession.java:1122)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.createProducer(JmsSessionImpl.java:1503)
                               : com.ibm.mq.jms.MQSession.createProducer(MQSession.java:661)
                               : com.ibm.mq.demo.TicketRequester.put(TicketRequester.java:86)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:65)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1870)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveInternal(WMQSyncConsumerShadow.java:229)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.receive(WMQConsumerShadow.java:1477)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.receive(WMQMessageConsumer.java:674)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receiveInboundMessage(JmsMessageConsumerImpl.java:1075)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receive(JmsMessageConsumerImpl.java:489)
                               : com.ibm.mq.jms.MQMessageConsumer.receive(MQMessageConsumer.java:179)
                               : com.ibm.mq.demo.TicketSubscriber.waitForPublish(TicketSubscriber.java:91)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:54)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.getMsg(WMQConsumerShadow.java:1870)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.receiveInternal(WMQSyncConsumerShadow.java:229)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.receive(WMQConsumerShadow.java:1477)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.receive(WMQMessageConsumer.java:674)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receiveInboundMessage(JmsMessageConsumerImpl.java:1075)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.receive(JmsMessageConsumerImpl.java:489)
                               : com.ibm.mq.jms.MQMessageConsumer.receive(MQMessageConsumer.java:179)
                               : com.ibm.mq.demo.TicketSubscriber.waitForPublish(TicketSubscriber.java:91)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:54)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.closeInternal(WMQSyncConsumerShadow.java:417)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.closeInternal(WMQConsumerShadow.java:294)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.close(WMQConsumerShadow.java:464)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.close(WMQConsumerShadow.java:319)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.close(WMQMessageConsumer.java:584)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.close(JmsMessageConsumerImpl.java:312)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:498)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:217)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.checkJmqiCallSuccess(WMQMessageConsumer.java:156)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.closeInternal(WMQSyncConsumerShadow.java:417)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.closeInternal(WMQConsumerShadow.java:294)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.close(WMQConsumerShadow.java:464)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.close(WMQConsumerShadow.java:319)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.close(WMQMessageConsumer.java:584)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.close(JmsMessageConsumerImpl.java:312)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:498)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:499)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1420)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1390)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:6598)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:599)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
                               : com.ibm.msg.client.wmq.internal.WMQSyncConsumerShadow.closeInternal(WMQSyncConsumerShadow.java:404)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.closeInternal(WMQConsumerShadow.java:294)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.close(WMQConsumerShadow.java:464)
                               : com.ibm.msg.client.wmq.internal.WMQConsumerShadow.close(WMQConsumerShadow.java:319)
                               : com.ibm.msg.client.wmq.internal.WMQMessageConsumer.close(WMQMessageConsumer.java:584)
                               : com.ibm.msg.client.jms.internal.JmsMessageConsumerImpl.close(JmsMessageConsumerImpl.java:312)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:498)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3810)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:571)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:780)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:154)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:499)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1420)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1390)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:6598)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:599)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:732)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3810)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:571)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:780)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:154)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:499)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1420)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1390)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:6598)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:599)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:732)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3810)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:571)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:780)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:154)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:499)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1420)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1390)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:6598)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:599)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:732)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3810)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:571)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:780)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:154)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:499)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1420)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1390)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:6598)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:599)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:732)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3810)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:571)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:780)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:154)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.checkJmqiCallSuccess(WMQMessageProducer.java:1282)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.access$400(WMQMessageProducer.java:76)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:759)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:499)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1420)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1390)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQCLOSE(RemoteFAP.java:6598)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQCLOSE(InterceptedJmqiImpl.java:599)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQCLOSE(ESEJMQI.java:315)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer$SpiIdentifiedProducerShadow.close(WMQMessageProducer.java:732)
                               : com.ibm.msg.client.wmq.internal.WMQMessageProducer.close(WMQMessageProducer.java:1333)
                               : com.ibm.msg.client.jms.internal.JmsMessageProducerImpl.close(JmsMessageProducerImpl.java:243)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:585)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3810)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:571)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:780)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:154)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
31 May 2020 3:37:53 AM[main] com.ibm.msg.client.wmq.internal.WMQConnection
Exception ignored as no exception listener is registered: '
                       Message : com.ibm.msg.client.jms.DetailedJMSException: JMSWMQ1107: A problem with this connection has occurred.
An error has occurred with the IBM MQ JMS connection.
Use the linked exception to determine the cause of this error.
                         Class : class com.ibm.msg.client.jms.DetailedJMSException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:825)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:776)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:644)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [1] --> Message : com.ibm.mq.MQException: JMSCMQ0001: IBM MQ call failed with compcode '2' ('MQCC_FAILED') reason '2009' ('MQRC_CONNECTION_BROKEN').
                         Class : class com.ibm.mq.MQException
                         Stack : com.ibm.msg.client.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:825)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:776)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:644)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [2] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteSession.getConnection(RemoteSession.java:499)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1420)
                               : com.ibm.mq.jmqi.remote.impl.RemoteSession.allocateMQAPI(RemoteSession.java:1390)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQDISC(RemoteFAP.java:1561)
                               : com.ibm.mq.jmqi.remote.api.RemoteFAP.MQDISC(RemoteFAP.java:1504)
                               : com.ibm.mq.ese.jmqi.InterceptedJmqiImpl.MQDISC(InterceptedJmqiImpl.java:431)
                               : com.ibm.mq.ese.jmqi.ESEJMQI.MQDISC(ESEJMQI.java:396)
                               : com.ibm.msg.client.wmq.internal.WMQSession.disconnect(WMQSession.java:813)
                               : com.ibm.msg.client.wmq.internal.WMQSession.close(WMQSession.java:776)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:644)
                               : com.ibm.msg.client.jms.internal.JmsSessionImpl.close(JmsSessionImpl.java:348)
                               : com.ibm.mq.jms.MQSession.close(MQSession.java:275)
                               : com.ibm.mq.demo.SessionBuilder.close(SessionBuilder.java:124)
                               : com.ibm.mq.demo.Reseller.main(Reseller.java:85)
     Caused by [3] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteConnection.asyncConnectionBroken(RemoteConnection.java:3810)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:571)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
     Caused by [4] --> Message : com.ibm.mq.jmqi.JmqiException: CC=2;RC=2009;AMQ9208: Error on receive from host 'localhost/127.0.0.1:1414 (localhost)'. [1=-1,2=ffffffff,3=localhost/127.0.0.1:1414 (localhost),4=TCP]
                         Class : class com.ibm.mq.jmqi.JmqiException
                         Stack : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveBuffer(RemoteRcvThread.java:780)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.receiveOneTSH(RemoteRcvThread.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteRcvThread.run(RemoteRcvThread.java:154)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1227)
'.

EXPLANATION:
An attempt was made to deliver an exception to the connections exception listener but a listener has not been registered.

ACTION:
An exception listener must be registered with the connection to receive its exceptions.
--------------------------------------------------------------------
